urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import redirect_to
from django.conf import settings
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'multichatapp.views.compose', name='compose'),
    url(r'^compose/', 'multichatapp.views.compose', name='compose'),
    url(r'^inbox/', 'multichatapp.views.inbox', name='inbox'),
    url(r'^profile/', 'multichatapp.views.profile', name='profile'),
    url(r'^accounts/profile/', redirect_to, {'url': '/'}),
    url(r'^signup/', 'multichatapp.views.registration', name='signup'),
    url(r'^accounts/login/', 'django.contrib.auth.views.login', name='authentication'),
    url(r'^accounts/logout/', 'multichatapp.views.logout_view', name='logout'),
          
    # url(r'^multichat/', include('multichat.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
     url(r'^admin/', include(admin.site.urls)),
#     (r'static/(?P<path>.*)$'), 'django.views.static.serve', {'document_root':settings.STATIC_ROOT}
)

multichatapp/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from datetime import datetime
from django.db.models.fields.related import ForeignKey
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from django.conf import settings

REGIONS= (
        ('Ungrouped','Ungrouped'),
        ('AS','Asia'),
        ('EU','Europe'),
        ('NA','North America'),
        ('SA','South America'),
        ('AF','Africa'),
        ('AN','Antartica'),
        ('OC','Oceania'),
)

SEX= (
      ('M', 'Male'),
      ('F', 'Female')
)
class Region(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=50)
    def __unicode__(self):
        return u"%s"%self.name
    class Meta:
        db_table = "jc_regions"
    
class UserProfile(models.Model):
    user = models.OneToOneField(User)
    region = models.ForeignKey(Region, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    sex_type = models.CharField(max_length=10, choices=SEX, null=True, blank=True)
    profile_pic_url = models.CharField(max_length=255, null=True, blank=True)
    class Meta:
        db_table = 'jc_user_profiles'
    def __unicode__(self):
        return u"%s"%(self.user)

class Message(models.Model) :
    title = models.CharField(max_length=255,blank=True,null=True) 
    body = models.TextField(blank=True,null=True)
    user= models.ForeignKey(User)
    created_at = models.DateTimeField(blank=True, default = datetime.now)
    updated_at = models.DateTimeField(default = datetime.now, blank=True)
    is_approved = models.PositiveSmallIntegerField(default = 0)
    members = models.ManyToManyField(User, related_name="messagem2m_set")
    def __unicode__ (self) :
            return u"%s"%(self.title)
    class Meta:
            db_table='jc_message'
                
#class Membership(models.Model):
#    user = models.ForeignKey(User)
#    message = models.ForeignKey(Message)
#    status = models.IntegerField(default = 0, blank=True, null=True) #0-unread, 1-read, 2-flagged
#    first_read_date = models.DateTimeField(blank=True, null=True)
#    def __unicode__ (self) :
#            return u"%s-%s"%(self.user, self.message)
#    class Meta:
#            db_table='jc_message_members'
#                

templates/base.html
{% comment %}
This template is a completely 100% generic HTML5 template.
{% endcomment %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="Prakhar K Goel">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Style (aka, calling Bootstrap) -->
    <link href="{{STATIC_URL}}css/bootstrap.min.css" rel="stylesheet">
    <link href="{{STATIC_URL}}css/bootstrap-responsive.min.css" rel="stylesheet">
    <!-- <link href="{{STATIC_URL}}css/bootstrap-1.1.1.css" rel="stylesheet"> -->

    <!-- Scripts, inc. TableSorter -->
    <script src="http://code.jquery.com/jquery-1.5.2.min.js"></script>
    <!-- <script src="{{STATIC_URL}}js/bootstrap-popover.js"></script> -->
    <!-- <script src="{{STATIC_URL}}js/bootstrap-tooltip.js"></script> -->
    <!-- <script src="{{STATIC_URL}}js/bootstrap.min.js"></script> -->
    
    {% block head %}{% endblock %}
  </head>
  <body>
  	{% block topnav %}{% endblock %}
  	
  	<div class="container">
	{% block content %}{% endblock %}
	{% block footer %}{% endblock %}
	</div>
  </body>
</html>

templates/compose.html
{% extends "topnav.html" %}
{% block head %}
    <title>Compose</title>
{% endblock %}


{% block content %}
<script>
	$(function () {
    $('.checkall').click(function () {
        $(this).parents('div:eq(0)').find(':checkbox').attr('checked', this.checked);
    });
});
</script>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span6">
        	<p>&nbsp;</p>
        	<p>&nbsp;</p>
          <h2 align="center">Create Message</h2>
          <p>&nbsp;</p>
			<!-- An exemplar signup form -->

			<form class="form-horizontal" method="POST">
				{% csrf_token %}
				{% if data.status %}
				    <p>{{data.status}}</p>
				{% endif %}
				
				{% for r in data.regions %}
				  <div class="control-group">
				    <label class="control-label">{{r.name}}</label>
				    <div class="controls">
				    {% for u in r.userprofile_set.all %}
		                <label class="checkbox">
		                    <input type="checkbox" name="usernames" value="{{u.user.pk}}"/>
		                    {{u.user.username}}
		                </label>
				    {% endfor %}
		                <label class="checkbox">
		                    <input type="checkbox" class="checkall"/>
		                    Select all in this group.
		                </label>
				    </div>
				  </div>
				{% endfor %}

				  <div class="control-group">
				    <label class="control-label">Subject</label>
				    <div class="controls">
				      <input type="text" name="subject" placeholder="Subject" value="{{data.title}}" />
				    </div>
				  </div>
				  <div class="control-group">
				    <label class="control-label">Message</label>
				    <div class="controls">
		                <textarea rows="5" name="message">{{data.body}}</textarea>
		                <span class="help-block">Type the message here</span>
				    </div>
				  </div>
				  <div class="control-group">
				    <div class="controls">
				      <button type="submit" class="btn btn-primary">Send Message</button>
				    </div>
				  </div>

			</form>
        </div>

        <div class="span4">
        	<p>&nbsp;</p>
        	<p>&nbsp;</p>
          <h2>Your Inbox Glimpse</h2>
          {% if data.messages.count > 0 %}
			<table class="table table-hover " >
				<thead>
				 <tr>
					<th>Time</th>
					<th>From</th>
					<th>Subject</th>
					<th>Message</th>
				 </tr>
				</thead>
				<tbody>
				{% for m in data.messages %}
				<tr>
					<td>
						<a href="#" class="" rel="popover" data-content="{{m.body}}" data-original-title="{{m.title}}">
							{{m.created_at|date:"j/n"}}
						</a>
					</td>
					<td>{{m.user.username}}</td>
					<td>{{m.title|slice:"10"}}{% if m.title|length > 10 %}...{% endif %}</td>
					<td>{{m.body|slice:"30"}}{% if m.body|length > 30 %}...{% endif %}</td>
				</tr>
				{% endfor %}
				</tbody>
			</table>
		  		
		  {% else %}
		  	<p>&nbsp;</p>
			<p>&nbsp;Your Inbox is empty brother.</p>
		  {% endif %}
        
        </div>
      
      </div> <!-- /row -->

{% endblock %}

templates/inbox.html
{% extends "topnav.html" %}
{% block head %}
    <title>Inbox</title>
{% endblock %}


{% block content %}

<div class="row">
	<div class="span7">
		<p>&nbsp;</p>
		<p>&nbsp;</p>
    	<h2 align="center">Inbox </h2>
		<p>&nbsp;</p>

		{% if data.messages.count > 0 %}
		<table class="table table-hover">
			<thead>
			<tr>
				<th>Id</th>
				<th>Subject</th>
				<th>Message</th>
				<th>From</th>
				<th>Timestamp</th>
			</tr>
			</thead>
			<tbody>
			{% for m in data.messages %}
			<tr>
				<td>{{m.pk}}</td>
				<td>{{m.title}}</td>
				<td>{{m.body}}</td>
				<td>{{m.user.username}}</td>
				<td>{{m.created_at|date:"j/n G:ia"}}</th>
			</tr>
			{% endfor %}
			</tbody>
		</table>
		{% else %}
		<p>&nbsp;</p>
		<p>&nbsp;Your Inbox is empty brother.</p>
		{% endif %}

    </div>
</div>

{% endblock %}

templates/login.html
{% extends "topnav.html" %}
{% block head %}
    <title>Welcome</title>
{% endblock %}

{% block content %}

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1></h1>
        
        <!--<p>Welcome to Multi-Chat</p>
        <p><a class="btn primary large">Learn more &raquo;</a></p>-->
        
      </div>
      
      <!-- Example row of columns -->
      <div class="row">
        <div class="span11">
           <h2 align="center">Login <!-- <small>and Signup</small> --></h2>
<p></p>


<!-- An exemplar signup form -->
{% if wrong_password %}
    <p>Your username and password didn't match, please try again.</p>
{% endif %}

<form action="" method="POST">
	{% csrf_token %}
                <fieldset>
                    <div class="clearfix">
                        <label>Username / Email</label>
                        <div class="input">
                            <input type="text" name="email" />
                        </div>
                    </div>
                    <div class="clearfix">
                        <label>Password</label>
                        <div class="input">
                            <input type="password" name="password" />
                        </div>
                    </div>
                    <div class="clearfix">
                        <div class="input">
                            <ul class="inputs-list">
                                <li>
                                </li>
								<li>
		                            <label>
		                                <input type="checkbox" />
		                                Remember Me
		                            </label>
								</li>
                            </ul>
                        </div>
                    </div>
                    <div class="actions">
                        <button class="btn primary">Go Baby Go</button>
                        <a class="btn">Reset</a>
                    </div>

                </fieldset>
            </form>
<p></p>

        </div>

<!-- The second column -->
        <div class="span5">
          <h2>Signup</h2>
           <p>There is no seperate process for signup. Just key in your email and password.</p>
           <ul>
           	<li>If you are visiting first time, you'll get registered.</li>
           	<li>If you have visited before and entered correct credentials, you'll be logged in.</li>
           	<li>If you have forgotten your password, may God bless you till I create a reset password option.</li>
           </ul>
<!-- <ul class="tabs">
  <li class="active"><a href="#"> </a></li>
  <li><a href="#"></a></li>
  <li><a href="#"></a></li>
</ul> -->
<p></p>
       </div>
      </div>

<!-- Footer -->
      <footer>
        <p>&copy; Company 2011</p>
      </footer>

    </div> <!-- /container -->

{% endblock %}

templates/profile.html
{% extends "topnav.html" %}
{% block head %}
    <title>Edit Profile</title>
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
    </style>
	<script type="text/javascript"
	  src="http://maps.google.com/maps/api/js?sensor=true"></script>
	<script type="text/javascript" src="http://gmaps-samples-v3.googlecode.com/svn/trunk/geolocate/geometa.js"></script>
    <script type="text/javascript">
      function initialize() {
      	// alert("hello");
        var mapOptions = {
          center: new google.maps.LatLng(-34.397, 150.644),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        // alert(mapOptions)
        var map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
	    prepareGeolocation();
	    doGeolocation();
        // alert(map)
      	document.getElementById("map_canvas").innerHTML = "Its working"
      }
      
  function doGeolocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(positionSuccess, positionError);
    } else {
      positionError(-1);
    }
  }

  function positionError(err) {
    var msg;
    switch(err.code) {
      case err.UNKNOWN_ERROR:
        msg = "Unable to find your location";
        break;
      case err.PERMISSION_DENINED:
        msg = "Permission denied in finding your location";
        break;
      case err.POSITION_UNAVAILABLE:
        msg = "Your location is currently unknown";
        break;
      case err.BREAK:
        msg = "Attempt to find location took too long";
        break;
      default:
        msg = "Location detection not supported in browser";
    }
    document.getElementById('info').innerHTML = msg;
  }

  function positionSuccess(position) {
    // Centre the map on the new location
    var coords = position.coords || position.coordinate || position;
    var latLng = new google.maps.LatLng(coords.latitude, coords.longitude);
    map.setCenter(latLng);
    map.setZoom(12);
    var marker = new google.maps.Marker({
	    map: map,
	    position: latLng,
	    title: 'Why, there you are!'
    });
    document.getElementById('info').innerHTML = 'Looking for <b>' +
        coords.latitude + ', ' + coords.longitude + '</b>...';

    // And reverse geocode.
    (new google.maps.Geocoder()).geocode({latLng: latLng}, function(resp) {
		  var place = "You're around here somewhere!";
		  if (resp[0]) {
			  var bits = [];
			  for (var i = 0, I = resp[0].address_components.length; i < I; ++i) {
				  var component = resp[0].address_components[i];
				  if (contains(component.types, 'political')) {
					  bits.push('<b>' + component.long_name + '</b>');
					}
				}
				if (bits.length) {
					place = bits.join(' > ');
				}
				marker.setTitle(resp[0].formatted_address);
			}
			document.getElementById('info').innerHTML = place;
	  });
  }

  function contains(array, item) {
	  for (var i = 0, I = array.length; i < I; ++i) {
		  if (array[i] == item) return true;
		}
		return false;
	}
      
      $(document).ready(function() {
		initialize()
 	});
    </script>
{% endblock %}

{% block content %}
      <!-- Example row of columns -->
      <div class="row">
        <div class="span6">

		  <p>&nbsp;</p>
		  <p>&nbsp;</p>
          <h2 align="center">Edit Profile ({{user.username}}) </h2>
          <p>&nbsp;</p>

			<!-- An exemplar signup form -->
			<form class="form-horizontal" method="POST">
			  {% csrf_token %}
				{% if data.status == 'success' %}
				    <p>Your profile is saved successfully.</p>
				{% endif %}

			  <div class="control-group">
			    <label class="control-label" for="id_username">Username</label>
			    <div class="controls">
			      <input type="text" id="id_username" name="username" value="{{data.username}}" readonly="readonly" />
			    </div>
			  </div>
			  <div class="control-group">
			    <label class="control-label" for="id_username">Username</label>
			    <div class="controls">
	                <select name="region">
	                	{% for r in data.regions %}
	                	{{data.current_region}} {{r.id}}
	                    <option value="{{r.id}}" {% ifequal data.current_region r.id %}selected="selected"{% endifequal %}>{{r.name}}</option>
	                    {% endfor %}
	                </select>
			    </div>
			  </div>
			  <div class="control-group">
			    <label class="control-label" for="id_password">Change Password</label>
			    <div class="controls">
			      <input type="password" id="id_password" name="password" placeholder="Password">
			    </div>
			  </div>
			  <div class="control-group">
			    <div class="controls">
			      <button type="submit" class="btn btn-primary">Save it</button>
			    </div>
			  </div>
			</form>
		</div>
        <div class="span4 offset2">
		  <p>&nbsp;</p>
		  <p>&nbsp;</p>
          <h2>Sidebar</h2>
          	<div id="map_canvas" class="span5">Hello</div>
	       	<div class="controls">&nbsp;</div>
	       	<div class="controls">&nbsp;</div>
	       	<div class="controls">&nbsp;</div>
	       	<div class="controls">&nbsp;</div>
       </div>
	  </div> <!-- /row -->
{% endblock %}

templates/profile_temp.html
{% extends "topnav.html" %}
{% block head %}
    <title>Welcome</title>

<script type="text/javascript"
  src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script type="text/javascript" src="http://gmaps-samples-v3.googlecode.com/svn/trunk/geolocate/geometa.js"></script>
<style type="text/css">
  /* *, html { margin:0; padding:0 }
  div#map_canvas { width:100%; height:100%; }
  div#info { width:100%; position:absolute; overflow:hidden; text-align:center; top:0;
    left:0; }*/
/*  .lightBox {
    filter:alpha(opacity=60);
    -moz-opacity:0.6;
    -khtml-opacity: 0.6;
    opacity: 0.6;
    background-color:white;
    padding:2px;
}*/
</style>
<script type="text/javascript">
  var map;
  function initialise() {
    var latlng = new google.maps.LatLng(-25.363882,131.044922);
    var myOptions = {
      zoom: 4,
      center: latlng,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      disableDefaultUI: true
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    prepareGeolocation();
    doGeolocation();
  }

  function doGeolocation() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(positionSuccess, positionError);
    } else {
      positionError(-1);
    }
  }

  function positionError(err) {
    var msg;
    switch(err.code) {
      case err.UNKNOWN_ERROR:
        msg = "Unable to find your location";
        break;
      case err.PERMISSION_DENINED:
        msg = "Permission denied in finding your location";
        break;
      case err.POSITION_UNAVAILABLE:
        msg = "Your location is currently unknown";
        break;
      case err.BREAK:
        msg = "Attempt to find location took too long";
        break;
      default:
        msg = "Location detection not supported in browser";
    }
    document.getElementById('info').innerHTML = msg;
  }

  function positionSuccess(position) {
    // Centre the map on the new location
    var coords = position.coords || position.coordinate || position;
    var latLng = new google.maps.LatLng(coords.latitude, coords.longitude);
    map.setCenter(latLng);
    map.setZoom(12);
    var marker = new google.maps.Marker({
	    map: map,
	    position: latLng,
	    title: 'Why, there you are!'
    });
    document.getElementById('info').innerHTML = 'Looking for <b>' +
        coords.latitude + ', ' + coords.longitude + '</b>...';

    // And reverse geocode.
    (new google.maps.Geocoder()).geocode({latLng: latLng}, function(resp) {
		  var place = "You're around here somewhere!";
		  if (resp[0]) {
			  var bits = [];
			  for (var i = 0, I = resp[0].address_components.length; i < I; ++i) {
				  var component = resp[0].address_components[i];
				  if (contains(component.types, 'political')) {
					  bits.push('<b>' + component.long_name + '</b>');
					}
				}
				if (bits.length) {
					place = bits.join(' > ');
				}
				marker.setTitle(resp[0].formatted_address);
			}
			document.getElementById('info').innerHTML = place;
	  });
  }

  function contains(array, item) {
	  for (var i = 0, I = array.length; i < I; ++i) {
		  if (array[i] == item) return true;
		}
		return false;
	}

</script>


{% endblock %}

{% block content %}
      <div class="row">
        <div class="span11">
           <h2 align="center">Edit Profile ({{user.username}}) <!-- <small>and Signup</small> --></h2>
			<p></p>

<!-- An exemplar signup form -->

<form method="POST">
	{% csrf_token %}
                <fieldset>
			        <div class="clearfix">
			            <div class="input">
							{% if data.status == 'success' %}
							    <p>Your profile is saved successfully.</p>
							{% endif %}
			            </div>
			        </div>
                	
                    <div class="clearfix">
                        	<label>Username</label>
                        <div class="input">
                            <input type="text" name="username" value="{{data.username}}" readonly="readonly"/>
                        </div>
                    </div>
                    <div class="clearfix">
                        	<label>Region</label>
                        <div class="input">
                            <select name="region">
                            	{% for r in data.regions %}
                            	{{data.current_region}} {{r.id}}
                                <option value="{{r.id}}" {% ifequal data.current_region r.id %}selected="selected"{% endifequal %}>{{r.name}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="clearfix">
                        	<label>Change Password</label>
                        <div class="input">
                            <input type="password" name="password" />
                        </div>
                    </div>		                     
                    <div class="actions">
                        <button class="btn primary">Save it</button>
                    </div>

                </fieldset>
</form>
<p></p>

        </div>

<!-- The second column -->
        <div class="span5">
        	<h2>Signup</h2>
			<div id="map_canvas">Hello world</div>
			<div id="info" class="span5 lightbox">Detecting your location...</div>
			<script>
				initialise()
			</script>
  
        	
          <!-- <h2>Signup</h2>
           <p>There is no seperate process for signup. Just key in your email and password.</p>
           <ul>
           	<li>If you are visiting first time, you'll get registered.</li>
           	<li>If you have visited before and entered correct credentials, you'll be logged in.</li>
           	<li>If you have forgotten your password, may God bless you till I create a reset password option.</li>
           </ul>
            -->
<!-- <ul class="tabs">
  <li class="active"><a href="#"> </a></li>
  <li><a href="#"></a></li>
  <li><a href="#"></a></li>
</ul> -->
<p></p>
       </div>
      </div>

<!-- Footer -->
      <footer>
        <p>&copy; Company 2011</p>
      </footer>

    </div> <!-- /container -->

{% endblock %}

templates/topnav.html
{% extends "base.html" %}

{% block topnav %}
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="#">MultiChat</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
                <li class="{% ifequal request.path "/" %}active{% endifequal %}"><a href="/">Home</a></li>
                {% if user.is_authenticated %}
                <li class="{% ifequal request.path "/compose/" %}active{% endifequal %}"><a href="{% url compose %}">Compose</a></li>
                <li class="{% ifequal request.path "/inbox/" %}active{% endifequal %}"><a href="{% url inbox %}">Inbox</a></li>
                <li class="{% ifequal request.path "/profile/" %}active{% endifequal %}"><a href="{% url profile %}">Edit Profile</a></li>
                {% else %}
                <li class="{% ifequal request.path "/signup/" %}active{% endifequal %}"><a href="{% url signup %}">Signup</a></li>
                {% endif %}

<!--               <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li> -->              
              
            </ul>
            {% if user.is_authenticated %}
            <ul class="nav pull-right">
            	<li><a>Welcome {{request.user.username}}</a></li>
            	<li><a href="{% url logout %}">Logout</a></li>
            </ul>
            {% endif %}
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    
{% endblock %}


{% block footer %}
<hr>
<!-- Footer -->
      <footer>
        <p>&copy; Prakhar Goel 2012</p>
      </footer>

{% endblock %}